# all units in kpc, Msolar, Myr
axis_length                 = 60.0
final_sim_time              = 1000.0
cfl                         = 0.1
num_data_dumps              = 128
total_mass                  = 3e+16
#particle_mass              = None
hbar_                       = 0.01
sim_name                    = "planeWave1d"
ntot                        = 1000000000000.0
k2_cutoff                   = 0.95
alias_threshold             = 0.001
dims                        = 1
size                        = 256

[ics]                         
type                        = "UserSpecified"
path                        = "planeWave1d.npz"

[cosmology]
omega_matter_now            = 1.0
omega_radiation_now         = 0.0
h                           = 1e-07
z0                          = 99.0
max_dloga                   = 0.01

[sampling]
num_streams = 128
seeds = "1 to 128"
scheme = "Wigner"