[package]
name = "msm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"
ndarray = { version = "0.15.4", features = ["rayon"] }
rustfft = "6.0.1"
transpose = "0.2.1"
conv = "0.3.3"
approx = "0.5.1"
rayon = "1.5.1"
clap = { version = "3.1.6", features = ["derive"] }
arrayfire = "3.8.0"
num = "0.4"