[package]
name = "msm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"
ndarray = "0.15.4"
rustfft = "6.0.1"
transpose = "0.2.1"