[package]
name = "msm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
transpose = "0.2.1"
conv = "0.3.3"
approx = "0.5.1"
clap = { version = "3.1.6", features = ["derive"] }
arrayfire = "3.7.4"
num = "0.2.1"
npy = "0.4"
npy-derive = "0.4"
ndarray = "0.15.4"
ndarray-npy = "0.8.1"

[features]
c64 = []