axis_length                 = 100
#time                        = 0 # Default is zero
final_sim_time              = 6
cfl                         = 0.4
num_data_dumps              = 200
total_mass                  = 1e9
#particle_mass              = None
hbar_                       = 0.02
sim_name                    = "bose-star-512"
k2_cutoff                   = 0.95
alias_threshold             = 0.02
dims                        = 3
size                        = 64
ics                         = { UserSpecified = { path = "/oak/stanford/orgs/kipac/users/pizza/MSM/rust/fake.npz" } }


