axis_length                 = 30
final_sim_time              = 400 # for drift multiple = 100 --> 71.6197243914
cfl                         = 0.5
num_data_dumps              = 1
total_mass                  = 1e10
#particle_mass              = None
hbar_                       = 0.02
sim_name                    = "gaussian-overdensity-512-mft"
k2_cutoff                   = 0.95
alias_threshold             = 0.02
dims                        = 3
size                        = 32

ics                         = { ColdGaussMFT = { mean = [15, 15, 15], std = [10, 10, 10] } } #, scheme = "Husimi", sample_seed = 0 } }

[cosmology]
omega_radiation_now = 0.0
omega_matter_now = 0.7
h = 0.7
z0 = 100.0
max_dloga = 1e-2