axis_length                 = 30
final_sim_time              = 400 # for drift multiple = 100 --> 71.6197243914
cfl                         = 0.02
num_data_dumps              = 200
total_mass                  = 1e10
#particle_mass              = None
hbar_                       = 0.02
sim_name                    = "gaussian-overdensity-512-mft"
k2_cutoff                   = 0.95
alias_threshold             = 0.02
dims                        = 3
size                        = 512

[ics]                         
type = "ColdGauss"
mean = [15, 15, 15]
std = [10, 10, 10]