axis_length                 = 30
final_sim_time              = 100
cfl                         = 0.001
num_data_dumps              = 200
total_mass                  = 1e10
#particle_mass              = None
hbar_                       = 0.02
sim_name                    = "gaussian-overdensity-512-mft"
k2_cutoff                   = 0.95
alias_threshold             = 0.02
dims                        = 3
size                        = 512

ics                         = { ColdGaussMFT = { mean = [15, 15, 15], std = [10, 10, 10] } } #, scheme = "Husimi", sample_seed = 0 } }


