axis_length                 = 30
final_sim_time              = 40
cfl                         = 0.5
num_data_dumps              = 200
total_mass                  = 1e11
#particle_mass              = None
hbar_                       = 0.05
sim_name                    = "spherical-tophat-cosmo"
k2_cutoff                   = 0.95
alias_threshold             = 0.02
dims                        = 3
size                        = 64


[ics]                         
type = "SphericalTophat"
radius = 5.0
slope = 50
delta = 100

[sampling]
seeds = "1 to 10"
scheme = "Husimi"

[cosmology]
omega_matter_now      = 0.7
omega_radiation_now   = 0.0
h                     = 0.7
z0                    = 1.0
max_dloga             = 0.01

[remote_storage_parameters]
keypair = "test.json"
storage_account = "science"